### ISSUE TITLE
Issue while executing object_tracker.py 

### ISSUE THREAD

**Issue by Ahsanr312** [theAIGuysCode/yolov3_deepsort#11]
I am using Google Colab for my computations. I followed everything as you have mentioned, but encountered this error while executing object_tracker.py
![Annotation 2020-05-12 094011](https://user-images.githubusercontent.com/39031891/81639274-e6d2b400-9434-11ea-88f7-2b5b0f476544.png)

**Comment by jacobsmith575161** [comment]
Help here, I had the same error what to do(using colab too)

**Comment by pythonmjs** [comment]
it will remove by commenting on the cv2.imshow and other cv2 functionalities.
