### ISSUE TITLE
Issue in generating result.avi file - nothing inside .avi file

### ISSUE THREAD

**Issue by snehitvaddi** [theAIGuysCode/yolov3_deepsort#6]
Hi man, I running "object_tracker.py" in Colab, it gives me this error: "cannot connect to X server" but generated a file named results.avi. I tried running in browser using commands
`!ffmpeg -i ./data/video/traffic-results2.avi ./data/video/output.mp4`

`from IPython.display import HTML`
`from base64 import b64encode`
`mp4 = open('./data/video/output.mp4','rb').read()`
`data_url = "data:video/mp4;base64," + b64encode(mp4).decode()`
`HTML("""
<video controls>
      <source src="%s" type="video/mp4">
</video>
""" % data_url)`
But output is displaying nothing. I even tried downloading .avi and while playing it, it is showing file is corrupt.

**Comment by theAIGuysCode** [comment]
I believe that is because this tutorial was not created for Google Colab, Google Colab can not output video.

**Comment by snehitvaddi** [comment]
👍

**Comment by ajithvallabai** [comment]
@snehitvaddi  did u get a output from colab or else u tried in desktop ?

**Comment by snehitvaddi** [comment]
I got it from colab itself. But the thing is, the output .avi file could not be played in parallel during processing. We need to download the output .avi file after all the execution had completed to see the results. I hope there is a way to calibrate both processing and playing in parallel and I am looking for it.
I guess you got my point!!

**Comment by ajithvallabai** [comment]
no @snehitvaddi  i got a empty file from colab i checked it even after downloading . Then i created a conda environment in pc only then it worked . Without conda it didnt work when i installed all packages by myself

**Comment by snehitvaddi** [comment]
Actually you need to wait until complete processing is done. It takes lot of time to process the entire video. It took me nearly 10-12 minutes for a 30 second video.

**Comment by jacobsmith575161** [comment]
> Actually you need to wait until complete processing is done. It takes lot of time to process the entire video. It took me nearly 10-12 minutes for a 30 second video.

I dont get how you ,made it work please explain, im facing the same error

**Comment by snehitvaddi** [comment]
Just follow the youtube tutorial and just be patient until everything is done.
Here is my repo along with output. Have a look at it here: https://github.com/snehitvaddi/YOLOv3-Object-Tracking
